### ISSUE TITLE
Add github convention LICENSE file

### ISSUE THREAD

**Issue by BroadcastGames** [retrobits/son_of_hunkypunk#35]
The Google project clearly says "GNU GPL v3" but over here on github the convention is to have a LICENSE.txt file in the root folder like the README.  "Most people place their license text in a file named LICENSE.txt (or LICENSE.md ) in the root of the repository".

Might want to mention the restrictions this places on distributing modified versions of the code.

**Comment by Dim8** [comment]
The licensing is placed in the source code, in the top of every class. And yes it is the **GNU GPL v3**. Here is a copy of it for your convenience:

    /*
	        Copyright © 2009 Rafał Rzepecki <divided.mind@gmail.com>

	        This file is part of Hunky Punk.

        Hunky Punk is free software: you can redistribute it and/or modify
        it under the terms of the GNU General Public License as published by
        the Free Software Foundation, either version 3 of the License, or
        (at your option) any later version.
        Hunky Punk is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        GNU General Public License for more details.
        You should have received a copy of the GNU General Public License
        along with Hunky Punk.  If not, see <http://www.gnu.org/licenses/>.
    */
It is more or less an artefact from the very first developer and has remained unchanged. All permissions and restrictions are mentioned in the license itself.

By the way, the GitHub citation goes on: *"As long as your intention is clear, you can place your license information wherever you like. "*
